language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
sudo: required
install:
  - make clean
  - make build
  - pip install codecov
script:
  - make test
  - coverage run -m unittest app/test/test_*.py
after_success:
  - codecov
