language: python
dist: xenial
python:
    - "3.7"
    - "3.6"
    - "3.5"
sudo: required
install:
  - make build
  - pip install codecov
script:
  - make test
  - coverage run -m unittest app/test/test_*.py
after_success:
  - codecov
