platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.8"

inputs:
- name: sdx-seft-publisher-service
  # path: gopath/github.com/ONSdigital/sdx-seft-publisher-service

run:
  path: ./sdx-seft-publisher-service/ci/launch.sh
